--------------------------------------------------------
--  File created - Monday-October-05-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CARS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USER1"."CARS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CLIENTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USER1"."CLIENTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORDERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USER1"."ORDERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CARS
--------------------------------------------------------

  CREATE TABLE "USER1"."CARS" 
   (	"IDCAR" NUMBER(6,0), 
	"MAKE" VARCHAR2(20 BYTE), 
	"MODEL" VARCHAR2(20 BYTE), 
	"MAKEYEAR" NUMBER(4,0), 
	"VIN" VARCHAR2(17 BYTE), 
	"IDCLIENT" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENTS
--------------------------------------------------------

  CREATE TABLE "USER1"."CLIENTS" 
   (	"NAME" VARCHAR2(20 BYTE), 
	"SURNAME" VARCHAR2(20 BYTE), 
	"BIRTHDAY" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"IDCLIENT" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "USER1"."ORDERS" 
   (	"IDORDER" NUMBER(10,0), 
	"IDCAR" NUMBER(6,0), 
	"DATEORDER" VARCHAR2(20 BYTE), 
	"ORDERCOST" NUMBER(5,0), 
	"ORDERSTATUS" VARCHAR2(15 BYTE), 
	"IDCLIENT" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into USER1.CARS
SET DEFINE OFF;
Insert into USER1.CARS (IDCAR,MAKE,MODEL,MAKEYEAR,VIN,IDCLIENT) values (1,'Kia','Rio',2014,'R578765783857564A',2);
Insert into USER1.CARS (IDCAR,MAKE,MODEL,MAKEYEAR,VIN,IDCLIENT) values (2,'Opel','Omega',1987,'F576787687878776F',1);
Insert into USER1.CARS (IDCAR,MAKE,MODEL,MAKEYEAR,VIN,IDCLIENT) values (12,'Asd','112as',1241,'Raa878475674874R',1);
REM INSERTING into USER1.CLIENTS
SET DEFINE OFF;
Insert into USER1.CLIENTS (NAME,SURNAME,BIRTHDAY,ADDRESS,PHONE,EMAIL,IDCLIENT) values ('Viktar','Karahoda','15-06-92','Minsk, Frolikova','5965277','victor1506@Mail.ru',1);
Insert into USER1.CLIENTS (NAME,SURNAME,BIRTHDAY,ADDRESS,PHONE,EMAIL,IDCLIENT) values ('Arkadz','Karahoda','27-01-91','Minsk, Gorodeckaya','8041714','zmey2701@tut.by',2);
Insert into USER1.CLIENTS (NAME,SURNAME,BIRTHDAY,ADDRESS,PHONE,EMAIL,IDCLIENT) values ('asaf','sdaa1we','1123','minsk','123141','asdasl@mail.ru',8);
REM INSERTING into USER1.ORDERS
SET DEFINE OFF;
Insert into USER1.ORDERS (IDORDER,IDCAR,DATEORDER,ORDERCOST,ORDERSTATUS,IDCLIENT) values (1,1,'15-10-2015',2000,'Completed',2);
Insert into USER1.ORDERS (IDORDER,IDCAR,DATEORDER,ORDERCOST,ORDERSTATUS,IDCLIENT) values (2,2,'02-12-2013',500,'Completed',1);
Insert into USER1.ORDERS (IDORDER,IDCAR,DATEORDER,ORDERCOST,ORDERSTATUS,IDCLIENT) values (15,1,'1235',2456,'In Progress',2);
--------------------------------------------------------
--  DDL for Index ORDERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER1"."ORDERS_PK" ON "USER1"."ORDERS" ("IDORDER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER1"."CLIENTS_PK" ON "USER1"."CLIENTS" ("IDCLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CARS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER1"."CARS_PK" ON "USER1"."CARS" ("IDCAR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "USER1"."ORDERS" MODIFY ("IDCLIENT" NOT NULL ENABLE);
  ALTER TABLE "USER1"."ORDERS" ADD CONSTRAINT "ORDERS_PK" PRIMARY KEY ("IDORDER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USER1"."ORDERS" MODIFY ("IDORDER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTS
--------------------------------------------------------

  ALTER TABLE "USER1"."CLIENTS" ADD CONSTRAINT "CLIENTS_PK" PRIMARY KEY ("IDCLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USER1"."CLIENTS" MODIFY ("IDCLIENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CARS
--------------------------------------------------------

  ALTER TABLE "USER1"."CARS" ADD CONSTRAINT "CARS_PK" PRIMARY KEY ("IDCAR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USER1"."CARS" MODIFY ("IDCAR" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CARS
--------------------------------------------------------

  ALTER TABLE "USER1"."CARS" ADD CONSTRAINT "IDCLIENT_FOREIGN_KEY" FOREIGN KEY ("IDCLIENT")
	  REFERENCES "USER1"."CLIENTS" ("IDCLIENT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "USER1"."ORDERS" ADD CONSTRAINT "IDCAR_FOREIGN_KEY" FOREIGN KEY ("IDCAR")
	  REFERENCES "USER1"."CARS" ("IDCAR") ENABLE;
--------------------------------------------------------
--  DDL for Trigger CARS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USER1"."CARS_TRG" 
BEFORE INSERT ON CARS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDCAR IS NULL THEN
      SELECT CARS_SEQ.NEXTVAL INTO :NEW.IDCAR FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "USER1"."CARS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CLIENTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USER1"."CLIENTS_TRG" 
BEFORE INSERT ON CLIENTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDCLIENT IS NULL THEN
      SELECT CLIENTS_SEQ.NEXTVAL INTO :NEW.IDCLIENT FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "USER1"."CLIENTS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ORDERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USER1"."ORDERS_TRG" 
BEFORE INSERT ON ORDERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDORDER IS NULL THEN
      SELECT ORDERS_SEQ.NEXTVAL INTO :NEW.IDORDER FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "USER1"."ORDERS_TRG" ENABLE;
